<?php

namespace Database\Seeders;

use App\Enums\BookingRequestStatus;
use App\Enums\BookingStatus;
use App\Enums\PaymentStatus;

class BookingSeedCatalog
{
    public static function scenarios(): array
    {
        return [
            [
                'booking_code' => 'BK-20260825-001',
                'customer_email' => 'andi.pratama@mail.test',
                'vehicle_plate' => 'B1234ABC',
                'service_name' => 'Ganti Oli Mesin',
                'mechanic_email' => 'budi@bengkelin.test',
                'start_at' => '2026-08-25 07:05:00',
                'actual_end_at' => '2026-08-25 07:40:00',
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::COMPLETED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Servis selesai lebih cepat dari estimasi.',
            ],
            [
                'booking_code' => 'BK-20260825-002',
                'customer_email' => 'maya@mail.test',
                'vehicle_plate' => 'D9012GHI',
                'service_name' => 'Ganti Kampas Rem',
                'mechanic_email' => 'andi@bengkelin.test',
                'start_at' => '2026-08-25 08:00:00',
                'actual_end_at' => '2026-08-25 09:00:00',
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::COMPLETED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Penggantian kampas rem depan dan belakang.',
            ],
            [
                'booking_code' => 'BK-20260825-003',
                'customer_email' => 'rizky@mail.test',
                'vehicle_plate' => 'B3456JKL',
                'service_name' => 'Servis Besar',
                'mechanic_email' => 'joko@bengkelin.test',
                'start_at' => '2026-08-25 09:30:00',
                'actual_end_at' => '2026-08-25 11:35:00',
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::FULLY_PAID,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Pelanggan langsung melunasi sisa pembayaran.',
            ],
            [
                'booking_code' => null,
                'customer_email' => 'putri@mail.test',
                'vehicle_plate' => 'B1122PQR',
                'service_name' => 'Cek & Isi Freon AC',
                'mechanic_email' => null,
                'start_at' => '2026-08-25 10:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::WAITING,
                'booking_status' => null,
                'payment_status' => null,
                'failure_reason' => 'Semua mekanik pada slot tersebut sudah terisi.',
                'notes' => null,
            ],
            [
                'booking_code' => 'BK-20260826-001',
                'customer_email' => 'fajar@mail.test',
                'vehicle_plate' => 'D3344STU',
                'service_name' => 'Tune Up Mesin',
                'mechanic_email' => 'rudi@bengkelin.test',
                'start_at' => '2026-08-26 07:30:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::PROCESSING,
                'booking_status' => BookingStatus::PENDING_PAYMENT,
                'payment_status' => PaymentStatus::PENDING,
                'failure_reason' => null,
                'notes' => 'Menunggu pembayaran DP dari customer.',
            ],
            [
                'booking_code' => 'BK-20260826-002',
                'customer_email' => 'diana@mail.test',
                'vehicle_plate' => 'L7788YZA',
                'service_name' => 'Perawatan CVT',
                'mechanic_email' => 'budi@bengkelin.test',
                'start_at' => '2026-08-26 09:15:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::WAITING,
                'booking_status' => BookingStatus::EXPIRED,
                'payment_status' => PaymentStatus::EXPIRED,
                'failure_reason' => 'Pembayaran DP kedaluwarsa.',
                'notes' => 'Invoice kedaluwarsa sebelum dibayar.',
            ],
            [
                'booking_code' => null,
                'customer_email' => 'agus@mail.test',
                'vehicle_plate' => 'B9900BCD',
                'service_name' => 'Ganti Ban',
                'mechanic_email' => null,
                'start_at' => '2026-08-26 11:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CANCELLED,
                'booking_status' => null,
                'payment_status' => null,
                'failure_reason' => 'Pengajuan dibatalkan oleh admin.',
                'notes' => null,
            ],
            [
                'booking_code' => 'BK-20260826-003',
                'customer_email' => 'lestari@mail.test',
                'vehicle_plate' => 'N2202HIJ',
                'service_name' => 'Servis Ringan',
                'mechanic_email' => 'joko@bengkelin.test',
                'start_at' => '2026-08-26 13:00:00',
                'actual_end_at' => '2026-08-26 14:00:00',
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::NO_SHOW,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Customer tidak datang sesuai jadwal.',
            ],
            [
                'booking_code' => 'BK-20260827-001',
                'customer_email' => 'hendra@mail.test',
                'vehicle_plate' => 'AB3303KLM',
                'service_name' => 'Servis Ringan',
                'mechanic_email' => 'andi@bengkelin.test',
                'start_at' => '2026-08-27 07:45:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::IN_PROGRESS,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Pengerjaan masih berlangsung.',
            ],
            [
                'booking_code' => 'BK-20260827-002',
                'customer_email' => 'nina@mail.test',
                'vehicle_plate' => 'P5505QRS',
                'service_name' => 'Ganti Oli Mesin',
                'mechanic_email' => 'dedi@bengkelin.test',
                'start_at' => '2026-08-27 09:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::CONFIRMED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Menunggu kendaraan masuk ke stall servis.',
            ],
            [
                'booking_code' => null,
                'customer_email' => 'andi.pratama@mail.test',
                'vehicle_plate' => 'B5678DEF',
                'service_name' => 'Ganti Ban',
                'mechanic_email' => null,
                'start_at' => '2026-08-27 09:10:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::WAITING,
                'booking_status' => null,
                'payment_status' => null,
                'failure_reason' => 'Slot pada jam tersebut masih bentrok dengan booking lain.',
                'notes' => null,
            ],
            [
                'booking_code' => 'BK-20260828-001',
                'customer_email' => 'maya@mail.test',
                'vehicle_plate' => 'D9012GHI',
                'service_name' => 'Cek & Isi Freon AC',
                'mechanic_email' => 'rudi@bengkelin.test',
                'start_at' => '2026-08-28 08:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::CONFIRMED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Jadwal servis AC mobil untuk hari berikutnya.',
            ],
            [
                'booking_code' => 'BK-20260828-002',
                'customer_email' => 'rizky@mail.test',
                'vehicle_plate' => 'L7890MNO',
                'service_name' => 'Perawatan CVT',
                'mechanic_email' => 'budi@bengkelin.test',
                'start_at' => '2026-08-28 10:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::PROCESSING,
                'booking_status' => BookingStatus::PENDING_PAYMENT,
                'payment_status' => PaymentStatus::PENDING,
                'failure_reason' => null,
                'notes' => 'Slot sudah di-reserve, menunggu pembayaran DP.',
            ],
            [
                'booking_code' => 'BK-20260829-001',
                'customer_email' => 'putri@mail.test',
                'vehicle_plate' => 'B1122PQR',
                'service_name' => 'Tune Up Mesin',
                'mechanic_email' => 'andi@bengkelin.test',
                'start_at' => '2026-08-29 08:15:00',
                'actual_end_at' => '2026-08-29 09:50:00',
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::COMPLETED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Perlu waktu tambahan untuk penyetelan akhir.',
            ],
            [
                'booking_code' => 'BK-20260829-002',
                'customer_email' => 'fajar@mail.test',
                'vehicle_plate' => 'B5566VWX',
                'service_name' => 'Ganti Kampas Rem',
                'mechanic_email' => 'joko@bengkelin.test',
                'start_at' => '2026-08-29 10:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::CONFIRMED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Booking terkonfirmasi untuk jadwal akhir pekan.',
            ],
            [
                'booking_code' => null,
                'customer_email' => 'diana@mail.test',
                'vehicle_plate' => 'L7788YZA',
                'service_name' => 'Servis Ringan',
                'mechanic_email' => null,
                'start_at' => '2026-08-29 11:30:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::EXPIRED,
                'booking_status' => null,
                'payment_status' => null,
                'failure_reason' => 'Pengajuan tidak dilanjutkan sampai batas waktu yang ditentukan.',
                'notes' => null,
            ],
            [
                'booking_code' => 'BK-20260830-001',
                'customer_email' => 'agus@mail.test',
                'vehicle_plate' => 'DK1101EFG',
                'service_name' => 'Ganti Oli Mesin',
                'mechanic_email' => 'dedi@bengkelin.test',
                'start_at' => '2026-08-30 07:00:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::CONFIRMED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Booking pembuka untuk hari Minggu.',
            ],
            [
                'booking_code' => 'BK-20260830-002',
                'customer_email' => 'hendra@mail.test',
                'vehicle_plate' => 'DK4404NOP',
                'service_name' => 'Servis Besar',
                'mechanic_email' => 'rudi@bengkelin.test',
                'start_at' => '2026-08-30 09:30:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::CONVERTED,
                'booking_status' => BookingStatus::CONFIRMED,
                'payment_status' => PaymentStatus::PAID,
                'failure_reason' => null,
                'notes' => 'Servis besar untuk kendaraan keluarga.',
            ],
            [
                'booking_code' => null,
                'customer_email' => 'nina@mail.test',
                'vehicle_plate' => 'P5505QRS',
                'service_name' => 'Ganti Ban',
                'mechanic_email' => null,
                'start_at' => '2026-08-30 09:45:00',
                'actual_end_at' => null,
                'request_status' => BookingRequestStatus::WAITING,
                'booking_status' => null,
                'payment_status' => null,
                'failure_reason' => 'Slot mekanik pada jam tersebut belum tersedia.',
                'notes' => null,
            ],
        ];
    }
}
